### ISSUE TITLE
does the whole omponent get rerender on changes?

### ISSUE THREAD

**Issue by boynet** [catberry/catberry-todomvc#10]
looking at the source it looks like the whole html is get rerender on changes, is it only in this demo or catberry dosent have virtual dom or something? thanks :)

**Comment by rdner** [comment]
Catberry does not have anything like Virtual DOM, it just replaces innerHTML of the component. But you can make components as small as you want and implement some kind of binding of value inside one element.

**Comment by rdner** [comment]
@boynet Since Catberry 6.0.0 has been released now it uses diff/patch algorithm for making DOM changes https://github.com/catberry/catberry/releases/tag/6.0.0
