### ISSUE TITLE
Implement debug-win script

### ISSUE THREAD

**Issue by insphere** [catberry/catberry-todomvc#11]
Current package.json contains scripts that don't run on Windows boxes. Please implement Windows version for convenience. Based on catberry-cli, it may be something like

"debug-win": "powershell -Command \"Start-Process -NoNewWindow node ./build.js; Start-Process -NoNewWindow -Wait ./node_modules/.bin/gulp; Start-Process -NoNewWindow -Wait node ./server.js\""

**Comment by rdner** [comment]
@insphere Thanks for noticing that, we just forgot about this repository.

So, as I understood the problem is just with a `debug` script, right?

**Comment by rdner** [comment]
Added the debug-win script in this release https://github.com/catberry/catberry-todomvc/releases/tag/0.7.2

**Comment by insphere** [comment]
Actually, npm start also doesn't work.

The error is: '.' is not recognized as an internal or external command. For debug one it just freezes and it's a bit complex to understand, what's happening.

**Comment by rdner** [comment]
Okay, I'll investigate the issue later.
