### ISSUE TITLE
Problem with line-height

### ISSUE THREAD

**Issue by reenko** [catberry/catberry-todomvc#19]
![image](https://cloud.githubusercontent.com/assets/11948740/14664554/ea4c7766-06ed-11e6-9b3a-f7ac1f3129d0.png)

**Comment by rdner** [comment]
More details? How did you get this state?

**Comment by reenko** [comment]
I added some empty items(pressed enter) and hovered for any item

**Comment by rdner** [comment]
Damn it! We need to forbid the empty value, thanks! :)
